name: Dev CDK Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: niacin-dev-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest-4-cores

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_SECRET }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Deploy using CDK
        run: |
          npm run cdk -- deploy --all -vv --require-approval never --concurrency 2
